const $=s=>document.querySelector(s), app=$('#app');
const bank={java:[
['Array Sum','Array Traversal','Easy','Amazon · Adobe',['public static int findSum(int[] arr) {','int sum = 0;','for (int i = 0; i < arr.length; i++) {','sum += arr[i];','}','return sum;','}'],'Initialize sum before the loop. Walk every element once and return the accumulated answer.','O(n)','O(1)'],
['Find Maximum','Array Traversal','Easy','Google · Oracle',['public static int findMax(int[] arr) {','int max = arr[0];','for (int i = 1; i < arr.length; i++) {','if (arr[i] > max) {','max = arr[i];','}','}','return max;','}'],'Start with the first value, then replace the maximum only when a larger value appears.','O(n)','O(1)'],
['Reverse String','Two Pointer','Easy','Microsoft · Meta',['public static void reverse(char[] text) {','int left = 0, right = text.length - 1;','while (left < right) {','char temp = text[left];','text[left] = text[right];','text[right] = temp;','left++;','right--;','}','}'],'Pointers start at opposite ends and move inward after each swap.','O(n)','O(1)'],
['Valid Parentheses','Stack','Medium','Amazon · Bloomberg',['public static boolean isValid(String s) {','Stack<Character> stack = new Stack<>();','for (char c : s.toCharArray()) {','if (c == \'(\') {','stack.push(c);','} else if (stack.isEmpty()) {','return false;','} else {','stack.pop();','}','}','return stack.isEmpty();','}'],'Push opening brackets. Closing brackets must match an existing opening bracket.','O(n)','O(n)']
],python:[
['Array Sum','Array Traversal','Easy','Google · Microsoft',['def find_sum(arr):','    total = 0','    for value in arr:','        total += value','    return total'],'Start the accumulator before visiting values. Add each value during one traversal.','O(n)','O(1)'],
['Find Maximum','Array Traversal','Easy','Amazon · Adobe',['def find_max(arr):','    maximum = arr[0]','    for value in arr[1:]:','        if value > maximum:','            maximum = value','    return maximum'],'Start with the first value, then replace it only when a larger one appears.','O(n)','O(1)'],
['Reverse String','Two Pointer','Easy','Meta · Netflix',['def reverse_text(chars):','    left, right = 0, len(chars) - 1','    while left < right:','        chars[left], chars[right] = chars[right], chars[left]','        left += 1','        right -= 1','    return chars'],'Pointers start at opposite ends and move inward after each swap.','O(n)','O(1)'],
['Valid Parentheses','Stack','Medium','Uber · Stripe',['def is_valid(text):','    stack = []','    for char in text:','        if char == \'(\':','            stack.append(char)','        elif not stack:','            return False','        else:','            stack.pop()','    return not stack'],'Push opening brackets. A close requires an available opening bracket.','O(n)','O(n)']
]};
let state=JSON.parse(localStorage.ca||'{}'),lang='java',blocks=[],attempts=0,start=Date.now(),timer;
function save(){localStorage.ca=JSON.stringify(state)}function esc(x){return x.replaceAll('&','&amp;').replaceAll('<','&lt;')}
function home(){app.innerHTML=`<section class="home"><div class="hero"><div class="brand"><i>◆</i> CODE ARCHITECT<small>™</small></div><div class="eyebrow" style="margin-top:70px">Powered by Kapil</div><h1>Think.<br>Arrange.<br><em style="color:var(--gold);font-style:normal">Compile.</em></h1><p>Can you rebuild the correct solution before time runs out? Train the logical sequencing that real engineers use.</p><div class="setup"><input id="name" placeholder="Your name" value="${state.name||''}"><select id="language"><option value="java">Java</option><option value="python">Python</option></select><button class="btn" onclick="begin()">Begin journey →</button></div><p style="font-size:12px;margin-top:17px">Offline-first · No login · Progress saved on this device</p></div></section>`;$('#language').value=state.lang||'java'}
function begin(){let n=$('#name').value.trim();if(!n)return $('#name').focus();state.name=n;lang=$('#language').value;state.lang=lang;state.xp??=0;state.solved??=0;state.position??=0;state.badges??=[];save();game()}
function current(){return bank[lang][state.position%bank[lang].length]}function badgeList(){let a=[];if(state.solved>=1)a.push('Array Builder');if(state.solved>=3)a.push('Flow Finder');if(state.solved>=5)a.push('Code Architect');return a}
function game(){document.querySelectorAll('.feedback').forEach(dialog=>dialog.remove());let q=current();attempts=0;start=Date.now();blocks=q[4].map((t,i)=>({t,i})).sort(()=>Math.random()-.5);app.innerHTML=`<div class="shell"><header class="top"><div class="brand"><i>◆</i> CODE ARCHITECT<small>™</small></div><div class="topnav"><span class="hide">${state.name}</span><span class="pill">${lang==='java'?'Java':'Python'}</span><span class="pill">⏱ <b id="clock">01:30</b></span><span class="pill gold">✦ ${state.xp} XP</span><button class="btn ghost" onclick="dashboard()">Dashboard</button></div></header><section class="stats"><div class="stat"><span>Current pattern</span><b>${q[1]}</b></div><div class="stat"><span>Challenge</span><b>${state.position+1} / ${bank[lang].length}</b></div><div class="stat"><span>Difficulty</span><b class="gold">${q[2]}</b></div><div class="stat"><span>Accuracy</span><b>${state.solved?Math.round((state.solved/(state.solved+(state.failed||0)))*100):0}%</b></div><div class="stat"><span>Mode</span><b>Practice</b></div></section><section class="challenge"><div class="workspace"><div class="problem"><div><div class="eyebrow">${q[1]} · ${q[2]}</div><h2>${q[0]}</h2><div class="meta"><span>${q[3]}</span><span>Est. 2 min</span><span>Read-only IDE</span></div></div><div class="pill gold">Arrange logic</div></div><div class="editorbar"><span>● ${lang==='java'?'Solution.java':'solution.py'}</span><span>Explorer · Code Architect</span></div><div class="code" id="code"></div><div class="actions"><button class="btn" onclick="compile()">▶ Compile</button><button class="btn ghost" onclick="hint()">Hint</button><button class="btn ghost" onclick="resetBlocks()">↻ Reset</button><button class="btn ghost" onclick="reveal()">Reveal</button></div></div><aside class="side"><div class="card"><h3>Build sequence</h3><div class="steps"><b>01</b> Declare function<br><b>02</b> Initialize variables<br><b>03</b> Control flow<br><b>04</b> Update state<br><b>05</b> Return result</div></div><div class="card"><h3>Architect’s note</h3><p class="hint">Don’t think about syntax. Trace the data: what must exist before the loop starts?</p></div><div class="card"><h3>Rewards</h3><div class="row"><span class="hint">First try</span><b class="gold">+200 XP</b></div><div class="row"><span class="hint">Second try</span><b>+100 XP</b></div></div></aside></section></div>`;render();clearInterval(timer);timer=setInterval(tick,1000)}
function render(){let c=$('#code');if(!c)return;c.innerHTML=blocks.map((b,n)=>`<div class="block" draggable="true" data-id="${b.i}"><span class="handle">⠿</span><span class="line">${String(n+1).padStart(2,'0')}</span><code>${esc(b.t)||' '}</code></div>`).join('');c.querySelectorAll('.block').forEach(x=>{x.ondragstart=e=>{e.dataTransfer.setData('id',x.dataset.id);x.classList.add('dragging')};x.ondragend=()=>x.classList.remove('dragging');x.ondragover=e=>e.preventDefault();x.ondrop=e=>{e.preventDefault();let id=+e.dataTransfer.getData('id'),from=blocks.findIndex(b=>b.i===id),to=blocks.findIndex(b=>b.i===+x.dataset.id);blocks.splice(to,0,blocks.splice(from,1)[0]);render()}})}
function tick(){let r=Math.max(0,90-Math.floor((Date.now()-start)/1000)),x=$('#clock');if(x)x.textContent=`${String(Math.floor(r/60)).padStart(2,'0')}:${String(r%60).padStart(2,'0')}`}
function compile(){let good=blocks.every((b,i)=>b.i===i);if(good){let completed=current();state.xp+=(attempts?100:200);state.solved++;state.position++;state.badges=badgeList();save();modal(true,completed)}else{attempts++;if(attempts===1)state.failed=(state.failed||0)+1;save();modal(false)}}
function modal(ok,completed){let q=completed||current(),content=ok?`<div class="eyebrow success">Compilation successful</div><h2>Logic, beautifully arranged.</h2><p>Challenge complete. Your next challenge is ready when you are.</p><div class="explain">${q[5]}\n\nTime: ${q[6]}   Space: ${q[7]}</div><button class="btn" onclick="game()">Next challenge →</button>`:`<div class="eyebrow error">Logical error detected</div><h2>Not quite in execution order.</h2><p>${attempts>=2?'Two attempts used. The correct order is now highlighted for review.':'A value is being used before it has been established. Follow: declare → initialize → iterate → return.'}</p><button class="btn ghost" onclick="this.closest('.feedback').remove()">Try again</button>${attempts>=2?'<button class="btn" onclick="reveal();this.closest(\'.feedback\').remove()">Show correct order</button>':''}`;document.body.insertAdjacentHTML('beforeend',`<div class="feedback"><div class="modal">${content}</div></div>`)}
function hint(){let q=current();document.body.insertAdjacentHTML('beforeend',`<div class="feedback"><div class="modal"><div class="eyebrow">Hint 1</div><h2>Start with the container.</h2><p>Your first line should create the function that holds the solution.</p><div class="explain">${esc(q[4][0])}</div><button class="btn" onclick="this.closest('.feedback').remove()">Got it</button></div></div>`)}function reveal(){blocks=current()[4].map((t,i)=>({t,i}));render()}function resetBlocks(){blocks=blocks.sort(()=>Math.random()-.5);render()}
function download(filename,text,type='text/plain'){let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=filename;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),300)}
function downloadProgress(){download('code-architect-progress.txt',`CODE ARCHITECT™\nPowered by Kapil\n\nStudent: ${state.name}\nLanguage: ${lang}\nXP: ${state.xp||0}\nChallenges completed: ${state.solved||0}\nBadges: ${(state.badges||[]).join(', ')||'None yet'}\nGenerated: ${new Date().toLocaleString()}`)}
function downloadBadge(name){download(`${name.toLowerCase().replaceAll(' ','-')}-badge.svg`,`<svg xmlns="http://www.w3.org/2000/svg" width="1000" height="600"><rect width="100%" height="100%" fill="#111112"/><rect x="30" y="30" width="940" height="540" rx="28" fill="none" stroke="#f6c851" stroke-width="5"/><text x="500" y="185" text-anchor="middle" fill="#f6c851" font-size="42" font-family="Arial">CODE ARCHITECT™</text><text x="500" y="300" text-anchor="middle" fill="#fff" font-size="74" font-weight="bold" font-family="Arial">${name}</text><text x="500" y="390" text-anchor="middle" fill="#aaa" font-size="30" font-family="Arial">Awarded to ${state.name}</text><text x="500" y="450" text-anchor="middle" fill="#aaa" font-size="24" font-family="Arial">Powered by Kapil · ${new Date().toLocaleDateString()}</text></svg>`,'image/svg+xml')}
function dashboard(){clearInterval(timer);let bd=state.badges||[];app.innerHTML=`<div class="shell dash"><header class="top"><div class="brand"><i>◆</i> CODE ARCHITECT<small>™</small></div><button class="btn" onclick="game()">Back to challenge</button></header><div class="eyebrow" style="margin-top:45px">${state.name}'s journey</div><h1 style="font-size:42px;letter-spacing:-2px;margin:8px 0 28px">Your architect dashboard</h1><div class="stats"><div class="stat"><span>XP earned</span><b class="gold">${state.xp||0}</b></div><div class="stat"><span>Level</span><b>${Math.floor((state.solved||0)/3)+1}</b></div><div class="stat"><span>Compilations</span><b>${state.solved||0}</b></div><div class="stat"><span>Badges</span><b>${bd.length} / 15</b></div><div class="stat"><span>Language</span><b>${lang}</b></div></div><div class="card"><div class="row"><h3>Pattern mastery</h3><b>${state.solved||0} / 36</b></div><p class="hint">Complete the curated challenge sequence. Your position is saved automatically.</p><div class="progress"><i style="width:${Math.min(100,((state.solved||0)/36)*100)}%"></i></div></div><div class="card" style="margin-top:16px"><h3>Downloads</h3><p class="hint">Keep a personal copy of your learning progress, or download unlocked badge artwork.</p><div class="actions" style="padding:0;border:0"><button class="btn" onclick="downloadProgress()">Download progress</button>${bd.map(x=>`<button class="btn ghost" onclick="downloadBadge('${x}')">Download ${x} badge</button>`).join('')}${!bd.length?'<span class="hint">Complete one challenge to unlock your first badge.</span>':''}</div></div></div>`}
home();
